FROM python:3.8

# pycacheを生成しないようにする
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade -r /code/requirements.txt

COPY ./src /code/src

CMD ["uvicorn", "src.server.local:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
