FROM public.ecr.aws/lambda/python:3.8

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade -r /code/requirements.txt

COPY ./src/server.py /code/src/server.py

CMD ["src.server.handler"]
